project:
  type: website

website:
  title: "Emily Tian"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: visual

